version: '3.8'

services:
  web:
    build: .
    container_name: hotel_web_local
    restart: always
    env_file:
      - .env.local
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-django-insecure-hx$$rau=sf86q@*-bu01+yzla%!b_*8g*pfddb3_mezm_h5ff(u}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-True}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
      - DB_NAME=${DB_NAME:-hotel_db}
      - DB_USER=${DB_USER:-hotel_user}
      - DB_PASSWORD=${DB_PASSWORD:-hotel_password}
      # Connect to host machine database
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_PORT=${DB_PORT:-3306}
      - TIME_ZONE=${TIME_ZONE:-Asia/Kolkata}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - hotel_network
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput --verbosity=0 &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 120 config.wsgi:application"

volumes:
  static_volume:
  media_volume:

networks:
  hotel_network:
    driver: bridge