version: '3.8'

services:
  web:
    build: .
    container_name: hotel_web_local
    restart: always
    env_file:
      - .env.local
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - TIME_ZONE=${TIME_ZONE}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - hotel_network
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput --verbosity=0 &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 120 config.wsgi:application"

volumes:
  static_volume:
  media_volume:

networks:
  hotel_network:
    driver: bridge