version: '3.8'

services:
  db:
    ports:
      - "3306:3306"

  redis:
    ports:
      - "6379:6379"

  web:
    volumes:
      - .:/app
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput --verbosity=0 &&
             python manage.py runserver 0.0.0.0:8000"