# Generated by Django 4.2.7 on 2025-11-25 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hotel_app.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('object_pk', models.CharField(blank=True, max_length=100, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('room_number', models.CharField(max_length=20)),
                ('booking_reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='building_images/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'building',
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('checklist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'checklist',
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=240, null=True)),
                ('required', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'checklist_item',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='department_logos/')),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='DepartmentRequestSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], max_length=20)),
                ('response_time_minutes', models.PositiveIntegerField(help_text='Response time in minutes')),
                ('resolution_time_minutes', models.PositiveIntegerField(help_text='Resolution time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'department_request_sla',
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('question_type', models.CharField(choices=[('rating', 'Rating (1-5)'), ('text', 'Free Text'), ('boolean', 'Yes / No')], default='text', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feedback_question',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'feedback_response',
                'ordering': ['received_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feedback_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('floor_name', models.CharField(max_length=50)),
                ('floor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('floor_number', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('rooms', models.PositiveIntegerField(default=0)),
                ('occupancy', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'floor',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=160, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('checkin_date', models.DateField(blank=True, null=True)),
                ('checkout_date', models.DateField(blank=True, null=True)),
                ('checkin_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Check-in Date & Time')),
                ('checkout_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Check-out Date & Time')),
                ('details_qr_code', models.TextField(blank=True, null=True, verbose_name='Guest Details QR Code (Base64)')),
                ('details_qr_data', models.TextField(blank=True, null=True, verbose_name='Guest Details QR Data')),
                ('breakfast_included', models.BooleanField(default=False)),
                ('guest_id', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('package_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GymMember',
            fields=[
                ('member_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_code', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('nik', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(max_length=128)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('confirm_password', models.CharField(max_length=128)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('plan_type', models.CharField(blank=True, max_length=50, null=True)),
                ('qr_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('unique_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scan_count', models.IntegerField(default=0)),
                ('scan_history', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'gym_member',
            },
        ),
        migrations.CreateModel(
            name='GymVisitor',
            fields=[
                ('visitor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gym_visitor',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('Inactive', 'Inactive')], default='active', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('location_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('pavilion', models.CharField(blank=True, max_length=120, null=True)),
                ('room_no', models.CharField(blank=True, max_length=40, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='locations', to='hotel_app.building')),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='LocationFamily',
            fields=[
                ('family_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'location_family',
            },
        ),
        migrations.CreateModel(
            name='RequestFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('request_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.checklist')),
                ('default_department', models.ForeignKey(blank=True, help_text='Department that typically handles this request type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_request_types', to='hotel_app.department')),
                ('request_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.requestfamily')),
            ],
            options={
                'db_table': 'request_type',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'db_table': 'section',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('room_no', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('escalated', 'Escalated'), ('rejected', 'Rejected')], default='pending', max_length=50, null=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('dashboard', 'Dashboard'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('other', 'Other')], default='web', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('sla_hours', models.FloatField(default=24, help_text='SLA time in hours to resolve')),
                ('sla_breached', models.BooleanField(default=False)),
                ('response_sla_hours', models.FloatField(default=1, help_text='SLA time in hours to respond')),
                ('response_sla_breached', models.BooleanField(default=False)),
                ('resolution_sla_breached', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('assignee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.department')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='hotel_app.guest')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.location')),
                ('request_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.requesttype')),
                ('requester_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_request',
            },
        ),
        migrations.CreateModel(
            name='SLAConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], max_length=20, unique=True)),
                ('response_time_minutes', models.PositiveIntegerField(help_text='Response time in minutes')),
                ('resolution_time_minutes', models.PositiveIntegerField(help_text='Resolution time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'slaconfiguration',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_groups', to='hotel_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('guest_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(default='91', max_length=5)),
                ('phone_number', models.CharField(max_length=15)),
                ('room_no', models.CharField(max_length=100)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('redeemed', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to=hotel_app.models.qr_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adults', models.IntegerField(default=1)),
                ('kids', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('qr_sent_whatsapp', models.BooleanField(default=False)),
                ('scan_count', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('valid_dates', models.JSONField(default=list)),
                ('scan_history', models.JSONField(blank=True, default=list)),
                ('include_breakfast', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.booking')),
            ],
            options={
                'db_table': 'voucher',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32, unique=True)),
                ('current_state', models.CharField(choices=[('idle', 'Idle'), ('awaiting_menu_selection', 'Awaiting Menu Selection'), ('awaiting_request_description', 'Awaiting Request Description'), ('feedback_invited', 'Feedback Invited'), ('collecting_feedback', 'Collecting Feedback')], default='idle', max_length=48)),
                ('last_known_guest_status', models.CharField(choices=[('unknown', 'Unknown'), ('pre_checkin', 'Pre Check-in'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], default='unknown', max_length=32)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('last_guest_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_system_message_at', models.DateTimeField(blank=True, null=True)),
                ('menu_presented_at', models.DateTimeField(blank=True, null=True)),
                ('welcome_sent_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_prompt_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='hotel_app.guest')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='hotel_app.voucher')),
            ],
            options={
                'db_table': 'whatsapp_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('role_hint', models.CharField(blank=True, max_length=120, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.workflow')),
            ],
            options={
                'ordering': ['workflow', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_expr', models.JSONField(blank=True, null=True)),
                ('from_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_from', to='hotel_app.workflowstep')),
                ('to_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_to', to='hotel_app.workflowstep')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=16)),
                ('body', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('error', models.TextField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hotel_app.whatsappconversation')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='hotel_app.guest')),
            ],
            options={
                'db_table': 'whatsapp_message',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('preferences', models.JSONField(blank=True, null=True)),
                ('role', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.usergroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnmatchedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('message_body', models.TextField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='pending', max_length=16)),
                ('notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='whatsapp', max_length=32)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unmatched_requests', to='hotel_app.whatsappconversation')),
                ('created_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_unmatched_requests', to='hotel_app.servicerequest')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmatched_requests', to='hotel_app.department')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmatched_requests', to='hotel_app.guest')),
                ('request_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmatched_requests', to='hotel_app.requesttype')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_unmatched_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'unmatched_request',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='TwilioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sid', models.CharField(blank=True, default='', max_length=64)),
                ('auth_token', models.CharField(blank=True, default='', max_length=128)),
                ('api_key_sid', models.CharField(blank=True, default='', max_length=64)),
                ('api_key_secret', models.CharField(blank=True, default='', max_length=128)),
                ('whatsapp_from', models.CharField(blank=True, default='', max_length=34)),
                ('test_to_number', models.CharField(blank=True, default='', max_length=34)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twilio_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Twilio Setting',
                'verbose_name_plural': 'Twilio Settings',
                'db_table': 'twilio_settings',
            },
        ),
        migrations.CreateModel(
            name='TicketReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=120, null=True)),
                ('room_no', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(db_index=True, max_length=50)),
                ('request_text', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('match_confidence', models.FloatField(default=0.0)),
                ('is_matched', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('moved_to_ticket', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.department')),
                ('matched_request_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.requesttype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.voucher')),
            ],
            options={
                'db_table': 'ticket_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.servicerequest')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.workflowstep')),
            ],
            options={
                'db_table': 'service_request_step',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.checklistitem')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.servicerequest')),
            ],
            options={
                'db_table': 'service_request_checklist',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.guest')),
            ],
        ),
        migrations.AddField(
            model_name='requesttype',
            name='work_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.workfamily'),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.workflow'),
        ),
        migrations.CreateModel(
            name='RequestKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='hotel_app.requesttype')),
            ],
            options={
                'db_table': 'request_keyword',
                'ordering': ['keyword'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success'), ('request', 'Service Request'), ('voucher', 'Voucher'), ('system', 'System')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='hotel_app.locationfamily')),
            ],
            options={
                'db_table': 'location_type',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.locationfamily'),
        ),
        migrations.AddField(
            model_name='location',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='hotel_app.floor'),
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.locationtype'),
        ),
        migrations.CreateModel(
            name='GymVisit',
            fields=[
                ('visit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('visit_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=240, null=True)),
                ('checked_by_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_app.gymmember')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_app.gymvisitor')),
            ],
            options={
                'db_table': 'gym_visit',
            },
        ),
        migrations.CreateModel(
            name='GuestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('comment_text', models.TextField()),
                ('linked_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.guest')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.location')),
            ],
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['guest_id'], name='hotel_app_g_guest_i_cfb667_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['room_number'], name='hotel_app_g_room_nu_f059bc_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['checkin_date', 'checkout_date'], name='hotel_app_g_checkin_8a4ee2_idx'),
        ),
        migrations.AddField(
            model_name='floor',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='floors', to='hotel_app.building'),
        ),
        migrations.AddField(
            model_name='feedbacksession',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_sessions', to='hotel_app.booking'),
        ),
        migrations.AddField(
            model_name='feedbacksession',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_sessions', to='hotel_app.whatsappconversation'),
        ),
        migrations.AddField(
            model_name='feedbacksession',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_sessions', to='hotel_app.guest'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='hotel_app.feedbackquestion'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='hotel_app.feedbacksession'),
        ),
        migrations.AddField(
            model_name='departmentrequestsla',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_configurations', to='hotel_app.department'),
        ),
        migrations.AddField(
            model_name='departmentrequestsla',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_configurations', to='hotel_app.requesttype'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.guest'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_app.checklist'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.location'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel_app.guest'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow', 'step_order')},
        ),
        migrations.AlterUniqueTogether(
            name='usergroupmembership',
            unique_together={('user', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='feedbackresponse',
            unique_together={('session', 'question')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_reference'], name='hotel_app_b_booking_c56f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in', 'check_out'], name='hotel_app_b_check_i_1839a6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room_number'], name='hotel_app_b_room_nu_68840a_idx'),
        ),
    ]
