# Generated by Django 4.2.7 on 2025-12-01 06:30

from django.db import migrations,models

# from hotel_app import models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    

        
    ]
