# Generated by Django 4.2.7 on 2025-10-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
