# Generated by Django 4.2.7 on 2025-12-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='guest_name',
        ),
    ]