# Generated by Django 4.2.7 on 2025-11-21 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_app', '0002_alter_location_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('question_type', models.CharField(choices=[('rating', 'Rating (1-5)'), ('text', 'Free Text'), ('boolean', 'Yes / No')], default='text', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feedback_question',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'db_table': 'section',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32, unique=True)),
                ('current_state', models.CharField(choices=[('idle', 'Idle'), ('awaiting_menu_selection', 'Awaiting Menu Selection'), ('awaiting_request_description', 'Awaiting Request Description'), ('feedback_invited', 'Feedback Invited'), ('collecting_feedback', 'Collecting Feedback')], default='idle', max_length=48)),
                ('last_known_guest_status', models.CharField(choices=[('unknown', 'Unknown'), ('pre_checkin', 'Pre Check-in'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], default='unknown', max_length=32)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('last_guest_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_system_message_at', models.DateTimeField(blank=True, null=True)),
                ('menu_presented_at', models.DateTimeField(blank=True, null=True)),
                ('welcome_sent_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_prompt_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='hotel_app.guest')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='hotel_app.voucher')),
            ],
            options={
                'db_table': 'whatsapp_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='requesttype',
            name='default_department',
            field=models.ForeignKey(blank=True, help_text='Department that typically handles this request type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_request_types', to='hotel_app.department'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='hotel_app.guest'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('dashboard', 'Dashboard'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('other', 'Other')], default='web', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=16)),
                ('body', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('error', models.TextField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hotel_app.whatsappconversation')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='hotel_app.guest')),
            ],
            options={
                'db_table': 'whatsapp_message',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='UnmatchedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('message_body', models.TextField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='pending', max_length=16)),
                ('notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='whatsapp', max_length=32)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unmatched_requests', to='hotel_app.whatsappconversation')),
                ('created_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_unmatched_requests', to='hotel_app.servicerequest')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmatched_requests', to='hotel_app.department')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmatched_requests', to='hotel_app.guest')),
                ('request_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmatched_requests', to='hotel_app.requesttype')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_unmatched_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'unmatched_request',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='TwilioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sid', models.CharField(blank=True, default='', max_length=64)),
                ('auth_token', models.CharField(blank=True, default='', max_length=128)),
                ('api_key_sid', models.CharField(blank=True, default='', max_length=64)),
                ('api_key_secret', models.CharField(blank=True, default='', max_length=128)),
                ('whatsapp_from', models.CharField(blank=True, default='', max_length=34)),
                ('test_to_number', models.CharField(blank=True, default='', max_length=34)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twilio_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Twilio Setting',
                'verbose_name_plural': 'Twilio Settings',
                'db_table': 'twilio_settings',
            },
        ),
        migrations.CreateModel(
            name='RequestKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='hotel_app.requesttype')),
            ],
            options={
                'db_table': 'request_keyword',
                'ordering': ['keyword'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_sessions', to='hotel_app.booking')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_sessions', to='hotel_app.whatsappconversation')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_sessions', to='hotel_app.guest')),
            ],
            options={
                'db_table': 'feedback_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='hotel_app.feedbackquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='hotel_app.feedbacksession')),
            ],
            options={
                'db_table': 'feedback_response',
                'ordering': ['received_at'],
                'unique_together': {('session', 'question')},
            },
        ),
    ]
