# Generated by Django 4.2.7 on 2025-12-29 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_add_ticket_comment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='hotel_app.building'),
        ),
        # migrations.AlterField(
        #     model_name='location',
        #     name='building',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='hotel_app.building'),
        # ),
    ]
