# Generated by Django 4.2.7 on 2025-12-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0005_alter_building_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='location_types/'),
        ),
    ]
