# Generated by Django 4.2.7 on 2025-11-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0006_twiliosettings_api_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='lead',
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
    ]
