# Generated by Django 4.2.7 on 2025-12-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0006_locationtype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymmember',
            name='country_code',
            field=models.CharField(default='91', max_length=5),
        ),
    ]
