# Generated by Django 4.2.7 on 2025-12-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0007_gymmember_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationfamily',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='location_family/'),
        ),
    ]
