# Generated by Django 4.2.7 on 2025-11-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0008_whatsapp_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('dashboard', 'Dashboard'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('other', 'Other')], default='web', max_length=20),
        ),
    ]
