# Generated by Django 4.2.7 on 2025-12-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0009'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('building', 'floor_name'), name='unique_floor_per_building'),
        ),
        migrations.AddConstraint(
            model_name='locationfamily',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_location_family_name'),
        ),
        migrations.AddConstraint(
            model_name='locationtype',
            constraint=models.UniqueConstraint(fields=('family', 'name'), name='unique_type_per_building'),
        ),
    ]
