# Generated by Django 4.2.7 on 2026-01-02 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0012_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel_app.locationfamily'),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel_app.locationtype'),
        ),
    ]
