# Generated by Django 4.2.7 on 2026-01-02 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0013_alter_location_family_alter_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='hotel_app.building'),
        ),
    ]
