# Generated by Django 4.2.7 on 2026-01-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0014_alter_location_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('building', 'name'), name='unique_location_name_per_building'),
        ),
    ]
