# Generated by Django 4.2.7 on 2026-01-12 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0015_alter_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_guests', to='hotel_app.location'),
        ),
    ]
