# Generated by Django 4.2.7 on 2026-01-12 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0016_guest_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_app.location'),
        ),
    ]
