# Generated by Django 4.2.7 on 2026-01-14 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_app', '0018_add_lost_and_found_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='FCM registration token', max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('web', 'Web Browser'), ('android', 'Android'), ('ios', 'iOS')], default='web', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fcm_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='fcm_token_user_id_25e98b_idx')],
            },
        ),
    ]
