# Generated by Django 4.2.7 on 2026-01-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0020_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostandfound',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lostandfound',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('found', 'Found'), ('returned', 'Returned to Guest')], default='open', max_length=20),
        ),
    ]
