# Generated by Django 4.2.7 on 2026-01-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0021_update_lost_and_found_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='facilities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
