# Generated by Django 4.2.7 on 2026-02-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0022_review_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmember',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
