# Generated by Django 4.2.7 on 2025-10-25 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hotel_app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_app', '0027_departmentrequestsla'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='breakfastvoucher',
        #     name='guest',
        # ),
        # migrations.RemoveField(
        #     model_name='breakfastvoucher',
        #     name='location',
        # ),
        # migrations.RemoveField(
        #     model_name='breakfastvoucherscan',
        #     name='scanned_by',
        # ),
        # migrations.RemoveField(
        #     model_name='breakfastvoucherscan',
        #     name='voucher',
        # ),
        # migrations.RemoveField(
        #     model_name='voucherscan',
        #     name='scanned_by_user',
        # ),
        # migrations.RemoveField(
        #     model_name='voucherscan',
        #     name='voucher',
        # ),
        migrations.DeleteModel(
            name='MasterLocation',
        ),
        migrations.DeleteModel(
            name='MasterUser',
        ),
        migrations.AlterModelOptions(
            name='departmentrequestsla',
            options={},
        ),
        migrations.AlterModelOptions(
            name='slaconfiguration',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='departmentrequestsla',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='servicerequestchecklist',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='servicerequeststep',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='building',
            name='id',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gymmember',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gymvisit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gymvisitor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='locationfamily',
            name='id',
        ),
        migrations.RemoveField(
            model_name='locationtype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='requesttype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='qr_image',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='building',
            name='building_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='building_images/'),
        ),
        migrations.AddField(
            model_name='building',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='checklist',
            name='checklist_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='item_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='department_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='floor',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='floor',
            name='floor_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floor',
            name='floor_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='occupancy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floor',
            name='rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='confirm_password',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymmember',
            name='customer_code',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymmember',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='member_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymmember',
            name='nik',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='password',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymmember',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='qr_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='scan_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='scan_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='unique_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='gymvisit',
            name='visit_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymvisitor',
            name='visitor_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='location_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='pavilion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('Inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='locationfamily',
            name='family_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationtype',
            name='family',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='hotel_app.locationfamily'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='locationtype',
            name='type_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesttype',
            name='request_type_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voucher',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.booking'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='country_code',
            field=models.CharField(default='91', max_length=5),
        ),
        migrations.AddField(
            model_name='voucher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='include_breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voucher',
            name='kids',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voucher',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='qr_code',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to=hotel_app.models.qr_upload_path),
        ),
        migrations.AddField(
            model_name='voucher',
            name='qr_sent_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voucher',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voucher',
            name='room_no',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='scan_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voucher',
            name='scan_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='voucher',
            name='valid_dates',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_app.checklist'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='floors', to='hotel_app.building'),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='address',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='gymvisit',
            name='checked_by_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gymvisit',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_app.gymmember'),
        ),
        migrations.AlterField(
            model_name='gymvisit',
            name='visit_at',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gymvisit',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_app.gymvisitor'),
        ),
        migrations.AlterField(
            model_name='gymvisitor',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gymvisitor',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='locations', to='hotel_app.building'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.locationfamily'),
        ),
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='hotel_app.floor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='room_no',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.locationtype'),
        ),
        migrations.AlterField(
            model_name='locationfamily',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='locationtype',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='guest_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='building',
            table='building',
        ),
        migrations.AlterModelTable(
            name='checklist',
            table='checklist',
        ),
        migrations.AlterModelTable(
            name='checklistitem',
            table='checklist_item',
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='departmentrequestsla',
            table='department_request_sla',
        ),
        migrations.AlterModelTable(
            name='floor',
            table='floor',
        ),
        migrations.AlterModelTable(
            name='gymmember',
            table='gym_member',
        ),
        migrations.AlterModelTable(
            name='gymvisit',
            table='gym_visit',
        ),
        migrations.AlterModelTable(
            name='gymvisitor',
            table='gym_visitor',
        ),
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
        migrations.AlterModelTable(
            name='locationfamily',
            table='location_family',
        ),
        migrations.AlterModelTable(
            name='locationtype',
            table='location_type',
        ),
        migrations.AlterModelTable(
            name='requesttype',
            table='request_type',
        ),
        migrations.AlterModelTable(
            name='servicerequest',
            table='service_request',
        ),
        migrations.AlterModelTable(
            name='servicerequestchecklist',
            table='service_request_checklist',
        ),
        migrations.AlterModelTable(
            name='servicerequeststep',
            table='service_request_step',
        ),
        migrations.AlterModelTable(
            name='slaconfiguration',
            table='slaconfiguration',
        ),
        migrations.AlterModelTable(
            name='voucher',
            table='voucher',
        ),
        migrations.DeleteModel(
            name='BreakfastVoucher',
        ),
        migrations.DeleteModel(
            name='BreakfastVoucherScan',
        ),
        migrations.DeleteModel(
            name='VoucherScan',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='id',
        ),
    ]
